In [2]:
import os
import torch
import numpy as np
import pickle
import pptk
import plotly
os.chdir("/user/jonathan.henrich/pptk")

In [ ]:
fig = px.scatter_3d(df, x='x', y='y', z='z', color="label" if labels_exist else None, \
                        size=size, opacity=0, size_max=5, template="plotly_dark")
    fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
    fig.update_traces(marker=dict(line=dict(width=4, color='Black')), selector=dict(mode='markers'))
    if show:
        fig.show()
    if write:
        fig.write_html(string + str(i) + ".html")

In [37]:
print(len(os.listdir("/user/jonathan.henrich/tree_learning/dataset/s3dis/preprocess")))
print(len(os.listdir("/user/jonathan.henrich/tree_learning/dataset/s3dis/preprocess_sample")))

270
270


In [38]:
conference_room = torch.load("/user/jonathan.henrich/tree_learning/dataset/s3dis/preprocess/Area_1_conferenceRoom_2_inst_nostuff.pth")

In [ ]:
colors = np.ones((len(points), 3)) * 255
v = pptk.viewer(points)
v.attributes(colors)
v.set(point_size=0.01)

In [39]:
len(conference_room[0])

1535040

In [ ]:
len(os.listdir())

In [27]:


##########save first entries of dataset and dataloader respectively############

# os.chdir("/user/jonathan.henrich/pptk")
# train_loader = torch.load("train_loader.pth")
# train_set = torch.load("train_set.pth")
# os.chdir("/user/jonathan.henrich/tree_learning")

# x = train_set[0]
# x = next(iter(train_loader))

# with open('trainset_0.pkl', 'wb') as f:
#     pickle.dump(x, f)
        
# with open('trainset_0.pkl', 'rb') as f:
#     loaded_dict = pickle.load(f)

# with open('trainloader_0.pkl', 'wb') as f:
#     pickle.dump(x, f)
        
# with open('trainloader_0.pkl', 'rb') as f:
#     loaded_dict = pickle.load(f)

########### investigate dataset######################

# train_set_0 = train_set[0]
# len(train_set_0)
# train_set_0[0]

In [37]:
with open('trainloader_0.pkl', 'rb') as f:
    trainloader_0 = pickle.load(f)

print(trainloader_0.keys())
for key,val in trainloader_0.items():
        exec(key + '=val')

dict_keys(['scan_ids', 'coords', 'batch_idxs', 'voxel_coords', 'p2v_map', 'v2p_map', 'coords_float', 'feats', 'semantic_labels', 'instance_labels', 'instance_pointnum', 'instance_cls', 'pt_offset_labels', 'spatial_shape', 'batch_size'])


In [38]:
# color = trainloader_0["coords"][:, 0]
# color = color.numpy()
# color = color[:, np.newaxis]
# color = (color + 1) * (pptk.rand(len(color), 3) / 4)

coords = coords[:, 1:]
coords = coords[::20]
coords = coords[batch_idxs[::20] == 0]
coords = coords.numpy()
print(len(coords))

color = pptk.rand(len(coords), 3)


v = pptk.viewer(coords)
v.attributes(color)
v.set(point_size=0.01)

10930


KeyboardInterrupt: 

In [30]:
x["voxel_coords"][:, 3].unique()

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [25]:
x["voxel_coords"]

tensor([[  0,  67,  28, 106],
        [  0, 108, 131, 137],
        [  0,  21,  65,  34],
        ...,
        [  3,  84,  85,   6],
        [  3,  92,  97, 116],
        [  3,  46,  21,  82]])

In [24]:
x["coords"]

tensor([[  0,  67,  28, 106],
        [  0, 108, 131, 137],
        [  0,  21,  65,  34],
        ...,
        [  3, 131, 109,  17],
        [  3,  92,  97, 116],
        [  3,  46,  21,  82]])

In [23]:
x["coords_float"]

tensor([[-32.6442,  15.4657,   3.3499],
        [-30.9897,  17.3058,   3.8222],
        [-32.5039,  16.0457,   1.6259],
        ...,
        [-22.2577, -16.0904,   4.3247],
        [-23.3600, -16.8502,   6.4003],
        [-23.6022, -18.0805,   5.0828]])

In [20]:
len(x["batch_idxs"])

468684

In [17]:
torch.unique(x["batch_idxs"])

tensor([0, 1, 2, 3], dtype=torch.int32)

In [3]:
xyz = pptk.rand(100, 3)
pptk.viewer(xyz)

In [4]:
pptk.viewer(xyz)

KeyboardInterrupt: 